services:
  mongo:
    image: mongo:7
    container_name: hbp-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: hbp_personal_site
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
